name: Deploy Site to GitHub Pages Repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v4

      - name: Deploy to Pages Repository
        run: |
          git config --global user.name "AyTechnic"
          git config --global user.email "actions@github.com"

          git clone https://x-access-token:${{ secrets.PAGES_TOKEN }}@github.com/AyTechnic/AyTechnic.github.io.git pages

          rsync -av --delete \
            --exclude '.git' \
            ./ pages/

          cd pages

          git add .
          git commit -m "Auto deploy from AyVPN-Site" || echo "No changes"

          git push
