name: Deploy Site to Pages Repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Deploy to Pages Repo
        env:
          TOKEN: ${{ secrets.PAGES_TOKEN }}
        run: |
          git config --global user.name "AyTechnic"
          git config --global user.email "actions@github.com"

          git clone https://x-access-token:$TOKEN@github.com/AyTechnic/AyTechnic.github.io.git pages

          rsync -av --delete --exclude='.git' ./ pages/

          cd pages

          git add .
          git commit -m "Auto deploy from private repo" || echo "No changes"

          git push
